// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ShelbyBackEnd.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial interface IShelbyECommContextProcedures
    {
        Task<int> Archive_CategoriesAsync(int? category_id, int? modified_by, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Insert_CategoriesAsync(int? parent_category_id, string category_name, int? display_order, short? default_sort_by_id, bool? hidden, string category_placement, bool? display_subcat_items, string alt_url, string alt_url_target, string link_title, string meta_title, string meta_desc, string meta_keywords, string search_tags, string category_desc, bool? category_desc_hidden, string category_short_desc, bool? category_short_desc_hidden, string category_secondary_desc, bool? category_secondary_desc_hidden, int? created_by, int? modified_by, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_All_CategoriesResult>> Select_All_CategoriesAsync(int? parentCatID, int? categoryid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_All_Categories_MenuResult>> Select_All_Categories_MenuAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_All_LowInventory_ProductsResult>> Select_All_LowInventory_ProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_All_Products_ListResult>> Select_All_Products_ListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_BackEnd_MenuResult>> Select_BackEnd_MenuAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_ProductResult>> Select_ProductAsync(long? prodID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_Search_ProductsResult>> Select_Search_ProductsAsync(string product_name, string product_code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Select_Sort_By_ListResult>> Select_Sort_By_ListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Update_CategoriesAsync(int? category_id, int? parent_category_id, string category_name, int? display_order, short? default_sort_by_id, bool? hidden, string category_placement, bool? display_subcat_items, string alt_url, string alt_url_target, string link_title, string meta_title, string meta_desc, string meta_keywords, string search_tags, string category_desc, bool? category_desc_hidden, string category_short_desc, bool? category_short_desc_hidden, string category_secondary_desc, bool? category_secondary_desc_hidden, int? modified_by, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
