// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_ProductResult
    {
        public long product_id { get; set; }
        [StringLength(30)]
        public string product_code { get; set; }
        [StringLength(50)]
        public string vendor_part_num { get; set; }
        [StringLength(25)]
        public string upc_code { get; set; }
        [StringLength(255)]
        public string product_name { get; set; }
        [StringLength(50)]
        public string product_short_name { get; set; }
        [Column("product_price", TypeName = "decimal(18,2)")]
        public decimal product_price { get; set; }
        public DateTime? start_date { get; set; }
        public DateTime? end_date { get; set; }
        public bool hidden { get; set; }
        public bool inactive { get; set; }
        public bool restricted { get; set; }
        public bool featured_item { get; set; }
        public long? parent_product_id { get; set; }
        public int? quantity { get; set; }
        public int? stock_amt { get; set; }
        public bool hide_outofstock { get; set; }
        public bool prevent_back_orders { get; set; }
        public short? low_stock_threshold { get; set; }
        public bool drop_ship_item { get; set; }
        public bool auto_po { get; set; }
        public double product_weight { get; set; }
        public double? product_length { get; set; }
        public double? product_width { get; set; }
        public double? product_height { get; set; }
        public bool allow_free_shipping { get; set; }
        [Column("fixed_shipping_cost", TypeName = "decimal(18,2)")]
        public decimal? fixed_shipping_cost { get; set; }
        [Column("fixed_shipping_cost_ext", TypeName = "decimal(12,2)")]
        public decimal? fixed_shipping_cost_ext { get; set; }
        public int? availability_id { get; set; }
        public bool show_availabilty_on_results { get; set; }
        public bool taxable { get; set; }
        [StringLength(25)]
        public string price_name { get; set; }
        [StringLength(255)]
        public string search_tags { get; set; }
        [StringLength(255)]
        public string meta_title { get; set; }
        [StringLength(2147483647)]
        public string meta_desc { get; set; }
        [StringLength(2147483647)]
        public string meta_keywords { get; set; }
        [StringLength(2147483647)]
        public string product_desc_short { get; set; }
        [StringLength(2147483647)]
        public string product_desc_above_price { get; set; }
        [StringLength(2147483647)]
        public string tab_product_desc { get; set; }
        [StringLength(25)]
        public string tab_product_desc_title { get; set; }
        [StringLength(2147483647)]
        public string tab_features { get; set; }
        [StringLength(25)]
        public string tab_features_title { get; set; }
        [StringLength(2147483647)]
        public string tab_specs { get; set; }
        [StringLength(25)]
        public string tab_specs_title { get; set; }
        [StringLength(2147483647)]
        public string tab_extra_info { get; set; }
        [StringLength(25)]
        public string tab_extra_info_title { get; set; }
        [StringLength(2147483647)]
        public string order_finish_note { get; set; }
        [Column("sale_price", TypeName = "decimal(18,2)")]
        public decimal? sale_price { get; set; }
        [Column("unit_cost", TypeName = "decimal(18,2)")]
        public decimal? unit_cost { get; set; }
        [Column("discount_price_level_1", TypeName = "decimal(18,2)")]
        public decimal? discount_price_level_1 { get; set; }
        [Column("discount_price_level_2", TypeName = "decimal(18,2)")]
        public decimal? discount_price_level_2 { get; set; }
        [Column("discount_price_level_3", TypeName = "decimal(18,2)")]
        public decimal? discount_price_level_3 { get; set; }
        [Column("discount_price_level_4", TypeName = "decimal(18,2)")]
        public decimal? discount_price_level_4 { get; set; }
        [Column("discount_price_level_5", TypeName = "decimal(18,2)")]
        public decimal? discount_price_level_5 { get; set; }
        [StringLength(255)]
        public string udf_1 { get; set; }
        [StringLength(255)]
        public string udf_2 { get; set; }
        [StringLength(255)]
        public string udf_3 { get; set; }
        [StringLength(255)]
        public string udf_4 { get; set; }
        [StringLength(255)]
        public string udf_5 { get; set; }
        public DateTime create_date { get; set; }
        public int? child_count { get; set; }
        public bool? in_stock { get; set; }
        public bool ships_by_itself { get; set; }
        public int? warehouse_id { get; set; }
        [StringLength(50)]
        public string warehouse_name { get; set; }
        [StringLength(10)]
        public string warehouse_code { get; set; }
        public string state_code { get; set; }
        [StringLength(50)]
        public string province { get; set; }
        [StringLength(15)]
        public string postal_code { get; set; }
        public string country_code { get; set; }
    }
}
