// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_All_LowInventory_ProductsResult
    {
        public long product_id { get; set; }
        [StringLength(30)]
        public string product_code { get; set; }
        [StringLength(255)]
        public string product_name { get; set; }
        [Column("product_price", TypeName = "decimal(18,2)")]
        public decimal product_price { get; set; }
        [StringLength(2147483647)]
        public string Categories { get; set; }
        public int quantity { get; set; }
        public bool hidden { get; set; }
        [StringLength(305)]
        public string photo_url { get; set; }
        public long? stockstatus { get; set; }
        public long? stocklowqtyalarm { get; set; }
        public long? lastpo_qty { get; set; }
        [StringLength(1)]
        public string addtopo_now { get; set; }
        public long? stockreorderqty { get; set; }
        [StringLength(10)]
        public string lastpo_date { get; set; }
    }
}
