// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_All_Categories_MenuResult
    {
        public int category_id { get; set; }
        public int parent_category_id { get; set; }
        [StringLength(50)]
        public string category_name { get; set; }
        public short? default_sort_by_id { get; set; }
        public bool display_subcat_items { get; set; }
        [StringLength(255)]
        public string alt_url { get; set; }
        [StringLength(10)]
        public string alt_url_target { get; set; }
        [StringLength(50)]
        public string link_title { get; set; }
        public long? voCatID { get; set; }
        public int? sub_count { get; set; }
    }
}
