// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_WarehouseResult
    {
        public int warehouse_id { get; set; }
        [StringLength(50)]
        public string warehouse_name { get; set; }
        [StringLength(10)]
        public string warehouse_code { get; set; }
        public string state_code { get; set; }
        [StringLength(50)]
        public string province { get; set; }
        [StringLength(15)]
        public string postal_code { get; set; }
        public string country_code { get; set; }
        public DateTime create_date { get; set; }
        public int? created_by { get; set; }
        public DateTime modified_date { get; set; }
        public int? modified_by { get; set; }
        public DateTime? deleted_date { get; set; }
        public long? voWarehouseID { get; set; }
    }
}
