// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_All_CategoriesResult
    {
        public int category_id { get; set; }
        public int parent_category_id { get; set; }
        [StringLength(50)]
        public string category_name { get; set; }
        public int display_order { get; set; }
        public short? default_sort_by_id { get; set; }
        public bool hidden { get; set; }
        [StringLength(10)]
        public string category_placement { get; set; }
        public bool display_subcat_items { get; set; }
        [StringLength(255)]
        public string alt_url { get; set; }
        [StringLength(10)]
        public string alt_url_target { get; set; }
        [StringLength(50)]
        public string link_title { get; set; }
        [StringLength(255)]
        public string meta_title { get; set; }
        [StringLength(255)]
        public string meta_desc { get; set; }
        [StringLength(2147483647)]
        public string meta_keywords { get; set; }
        [StringLength(255)]
        public string search_tags { get; set; }
        [StringLength(2147483647)]
        public string category_desc { get; set; }
        public bool category_desc_hidden { get; set; }
        [StringLength(2147483647)]
        public string category_short_desc { get; set; }
        public bool category_short_desc_hidden { get; set; }
        [StringLength(2147483647)]
        public string category_secondary_desc { get; set; }
        public bool category_secondary_desc_hidden { get; set; }
        public DateTime create_date { get; set; }
        public int? created_by { get; set; }
        public DateTime modified_date { get; set; }
        public int? modified_by { get; set; }
        public DateTime? deleted_date { get; set; }
        public long? voCatID { get; set; }
        public int? sub_count { get; set; }
        [StringLength(1)]
        public string file_path { get; set; }
    }
}
