// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_BackEnd_MenuResult
    {
        public int backend_menu_id { get; set; }
        public int parent_backend_menu_id { get; set; }
        [StringLength(50)]
        public string backend_menu_name { get; set; }
        [StringLength(50)]
        public string alt_url { get; set; }
        public int display_order { get; set; }
        public DateTime create_date { get; set; }
        public int? created_by { get; set; }
        public DateTime modified_date { get; set; }
        public int? modified_by { get; set; }
        public DateTime? deleted_date { get; set; }
    }
}
