// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class Select_Sort_By_ListResult
    {
        public short sort_by_id { get; set; }
        [StringLength(25)]
        public string sort_by_desc { get; set; }
        public short display_order { get; set; }
        [StringLength(25)]
        public string sort_code { get; set; }
        public bool is_default { get; set; }
    }
}
