// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ShelbyBackEnd.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ShelbyBackEnd.Infrastructure.Models
{
    public partial class ShelbyECommContext
    {
        private IShelbyECommContextProcedures _procedures;

        public virtual IShelbyECommContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ShelbyECommContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IShelbyECommContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ShelbyECommContextProcedures : IShelbyECommContextProcedures
    {
        private readonly ShelbyECommContext _context;

        public ShelbyECommContextProcedures(ShelbyECommContext context)
        {
            _context = context;
        }

        public virtual async Task<int> Archive_CategoriesAsync(int? category_id, int? modified_by, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "category_id",
                    Value = category_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "modified_by",
                    Value = modified_by ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Archive_Categories] @category_id = @category_id, @modified_by = @modified_by", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Insert_CategoriesAsync(int? parent_category_id, string category_name, int? display_order, short? default_sort_by_id, bool? hidden, string category_placement, bool? display_subcat_items, string alt_url, string alt_url_target, string link_title, string meta_title, string meta_desc, string meta_keywords, string search_tags, string category_desc, bool? category_desc_hidden, string category_short_desc, bool? category_short_desc_hidden, string category_secondary_desc, bool? category_secondary_desc_hidden, int? created_by, int? modified_by, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "parent_category_id",
                    Value = parent_category_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "category_name",
                    Size = 50,
                    Value = category_name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "display_order",
                    Value = display_order ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "default_sort_by_id",
                    Value = default_sort_by_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "hidden",
                    Value = hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "category_placement",
                    Size = 10,
                    Value = category_placement ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "display_subcat_items",
                    Value = display_subcat_items ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "alt_url",
                    Size = 255,
                    Value = alt_url ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "alt_url_target",
                    Size = 10,
                    Value = alt_url_target ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "link_title",
                    Size = 50,
                    Value = link_title ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "meta_title",
                    Size = 255,
                    Value = meta_title ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "meta_desc",
                    Size = 255,
                    Value = meta_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "meta_keywords",
                    Size = -1,
                    Value = meta_keywords ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "search_tags",
                    Size = 255,
                    Value = search_tags ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_desc",
                    Size = -1,
                    Value = category_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_desc_hidden",
                    Value = category_desc_hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "category_short_desc",
                    Size = -1,
                    Value = category_short_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_short_desc_hidden",
                    Value = category_short_desc_hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "category_secondary_desc",
                    Size = -1,
                    Value = category_secondary_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_secondary_desc_hidden",
                    Value = category_secondary_desc_hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "created_by",
                    Value = created_by ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "modified_by",
                    Value = modified_by ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Insert_Categories] @parent_category_id = @parent_category_id, @category_name = @category_name, @display_order = @display_order, @default_sort_by_id = @default_sort_by_id, @hidden = @hidden, @category_placement = @category_placement, @display_subcat_items = @display_subcat_items, @alt_url = @alt_url, @alt_url_target = @alt_url_target, @link_title = @link_title, @meta_title = @meta_title, @meta_desc = @meta_desc, @meta_keywords = @meta_keywords, @search_tags = @search_tags, @category_desc = @category_desc, @category_desc_hidden = @category_desc_hidden, @category_short_desc = @category_short_desc, @category_short_desc_hidden = @category_short_desc_hidden, @category_secondary_desc = @category_secondary_desc, @category_secondary_desc_hidden = @category_secondary_desc_hidden, @created_by = @created_by, @modified_by = @modified_by", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Select_All_CategoriesResult>> Select_All_CategoriesAsync(int? parentCatID, int? categoryid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ParentCatID",
                    Value = parentCatID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "categoryid",
                    Value = categoryid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Select_All_CategoriesResult>("EXEC @returnValue = [dbo].[Select_All_Categories] @ParentCatID = @ParentCatID, @categoryid = @categoryid", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Select_All_Categories_MenuResult>> Select_All_Categories_MenuAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Select_All_Categories_MenuResult>("EXEC @returnValue = [dbo].[Select_All_Categories_Menu]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Select_BackEnd_MenuResult>> Select_BackEnd_MenuAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Select_BackEnd_MenuResult>("EXEC @returnValue = [dbo].[Select_BackEnd_Menu]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Select_Sort_By_ListResult>> Select_Sort_By_ListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Select_Sort_By_ListResult>("EXEC @returnValue = [dbo].[Select_Sort_By_List]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Update_CategoriesAsync(int? category_id, int? parent_category_id, string category_name, int? display_order, short? default_sort_by_id, bool? hidden, string category_placement, bool? display_subcat_items, string alt_url, string alt_url_target, string link_title, string meta_title, string meta_desc, string meta_keywords, string search_tags, string category_desc, bool? category_desc_hidden, string category_short_desc, bool? category_short_desc_hidden, string category_secondary_desc, bool? category_secondary_desc_hidden, int? modified_by, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "category_id",
                    Value = category_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "parent_category_id",
                    Value = parent_category_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "category_name",
                    Size = 50,
                    Value = category_name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "display_order",
                    Value = display_order ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "default_sort_by_id",
                    Value = default_sort_by_id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "hidden",
                    Value = hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "category_placement",
                    Size = 10,
                    Value = category_placement ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "display_subcat_items",
                    Value = display_subcat_items ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "alt_url",
                    Size = 255,
                    Value = alt_url ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "alt_url_target",
                    Size = 10,
                    Value = alt_url_target ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "link_title",
                    Size = 50,
                    Value = link_title ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "meta_title",
                    Size = 255,
                    Value = meta_title ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "meta_desc",
                    Size = 255,
                    Value = meta_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "meta_keywords",
                    Size = -1,
                    Value = meta_keywords ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "search_tags",
                    Size = 255,
                    Value = search_tags ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_desc",
                    Size = -1,
                    Value = category_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_desc_hidden",
                    Value = category_desc_hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "category_short_desc",
                    Size = -1,
                    Value = category_short_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_short_desc_hidden",
                    Value = category_short_desc_hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "category_secondary_desc",
                    Size = -1,
                    Value = category_secondary_desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "category_secondary_desc_hidden",
                    Value = category_secondary_desc_hidden ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "modified_by",
                    Value = modified_by ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Update_Categories] @category_id = @category_id, @parent_category_id = @parent_category_id, @category_name = @category_name, @display_order = @display_order, @default_sort_by_id = @default_sort_by_id, @hidden = @hidden, @category_placement = @category_placement, @display_subcat_items = @display_subcat_items, @alt_url = @alt_url, @alt_url_target = @alt_url_target, @link_title = @link_title, @meta_title = @meta_title, @meta_desc = @meta_desc, @meta_keywords = @meta_keywords, @search_tags = @search_tags, @category_desc = @category_desc, @category_desc_hidden = @category_desc_hidden, @category_short_desc = @category_short_desc, @category_short_desc_hidden = @category_short_desc_hidden, @category_secondary_desc = @category_secondary_desc, @category_secondary_desc_hidden = @category_secondary_desc_hidden, @modified_by = @modified_by", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
